### ISSUE TITLE
Error HH8: There's one or more errors in your config file:

### ISSUE THREAD

**Issue by Neharoy2022** [PatrickAlphaC/hardhat-simple-storage-fcc#13]

**Comment by Neharoy2022** [comment]
Error (HH8) occurs during deployment (@ video 08:50:00 )
* Invalid value undefined for HardhatConfig.networks.rinkeby.url - Expected a value of type string.
  * Invalid account: #0 for network: rinkeby - Expected string, received undefined
 
Note:   No error occurs when I am directly writing the URL link within quotes and private key.

code below:
``` solidity

require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config();

/** @type import('hardhat/config').HardhatUserConfig */

const RINKEBY_RPC_URL = process.env.RINKEBY_RPC_URL;
const PRIVATE_KEY = process.env.PRIVATE_KEY;
module.exports = {
  defaultNetwork: "hardhat",
  networks: {
    rinkeby: {
      url: RINKEBY_RPC_URL,
      accounts: [PRIVATE_KEY],
      chainId: 4,
    },
  },
  solidity: "0.8.8",
};
```

**Comment by PatrickAlphaC** [comment]
Closing, please ask questions in the discussions tab of the full repo.

Also, it looks like you just need your private key in your .env file as @mattaereal said. 

https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
