### ISSUE TITLE
RPC_URL in .env should be names KOVAN_RPC_URL

### ISSUE THREAD

**Issue by ansund** [PatrickAlphaC/hardhat-simple-storage-fcc#2]
It is KOVAN_RPC_URL in hardhat.config.js and in the readme.

**Comment by ansund** [comment]
I made a pull request with the fix. :-)

Thank you for a fantastic course! I'm going from knowing nothing about blockchain to feeling more and more comfortable so fast!

**Comment by PatrickAlphaC** [comment]
Yes!!!
