### ISSUE TITLE
yarn hardhat run scripts/deploy.js --network rinkeby

### ISSUE THREAD

**Issue by fayazap** [PatrickAlphaC/hardhat-simple-storage-fcc#20]
Error HH801: Plugin @nomicfoundation/hardhat-toolbox requires the following dependencies to be installed: @nomicfoundation/hardhat-network-helpers, @nomicfoundation/hardhat-chai-matchers, @types/mocha, @typechain/ethers-v5, @typechain/hardhat, ts-node, typescript.

**Comment by PatrickAlphaC** [comment]
Can you please add how you got this error from git clone to here? 

I cannot reproduce this issue.
