### ISSUE TITLE
I keep getting this error while running tests for the simple storage contract in hardhat in lesson 6

### ISSUE THREAD

**Issue by FarhanAnis005** [PatrickAlphaC/hardhat-simple-storage-fcc#31]
```
SimpleStorage

    1) Should start with a fav no of zero


  0 passing (2s)
  1 failing

  1) SimpleStorage
       Should start with a fav no of zero:

      ```
AssertionError: expected 'function () {\n        var args = [];…' to equal '0'
      + expected - actual

      -function () {
      -        var args = [];
      -        for (var _i = 0; _i < arguments.length; _i++) {
      -            args[_i] = arguments[_i];
      -        }
      -        return __awaiter(this, void 0, void 0, function () {
      -            var blockTag, overrides, tx, result, value;
      -            return __generator(this, function (_a) {
      -                switch (_a.label) {
      -                    case 0:
      -                        blockTag = undefined;
      -                        if (!(args.length === fragment.inputs.length + 1 && typeof (args[args.length - 1]) === "object")) return [3 /*break*/, 3];   
      -                        overrides = (0, properties_1.shallowCopy)(args.pop());
      -                        if (!(overrides.blockTag != null)) return [3 /*break*/, 2];
      -                        return [4 /*yield*/, overrides.blockTag];
      -                    case 1:
      -                        blockTag = _a.sent();
      -                        _a.label = 2;
      -                    case 2:
      -                        delete overrides.blockTag;
      -                        args.push(overrides);
      -                        _a.label = 3;
      -                    case 3:
      -                        if (!(contract.deployTransaction != null)) return [3 /*break*/, 5];
      -                        return [4 /*yield*/, contract._deployed(blockTag)];
      -                    case 4:
      -                        _a.sent();
      -                        _a.label = 5;
      -                    case 5: return [4 /*yield*/, populateTransaction(contract, fragment, args)];
      -                    case 6:
      -                        tx = _a.sent();
      -                        return [4 /*yield*/, signerOrProvider.call(tx, blockTag)];
      -                    case 7:
      -                        result = _a.sent();
      -                        try {
      -                            value = contract.interface.decodeFunctionResult(fragment, result);
      -                            if (collapseSimple && fragment.outputs.length === 1) {
      -                                value = value[0];
      -                            }
      -                            return [2 /*return*/, value];
      -                        }
      -                        catch (error) {
      -                            if (error.code === logger_1.Logger.errors.CALL_EXCEPTION) {
      -                                error.address = contract.address;
      -                                error.args = args;
      -                                error.transaction = tx;
      -                            }
      -                            throw error;
      -                        }
      -                        return [2 /*return*/];
      -                }
      -            });
      -        });
      -    }
      +0

      at Context.<anonymous> (test\test-deploy.js:14:16)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)

```

error Command failed with exit code 1.
```

Can anyone please help me

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
