### ISSUE TITLE
WslRegisterDistribution failed with error

### ISSUE THREAD

**Issue by allanthuranira** [PatrickAlphaC/hardhat-simple-storage-fcc#35]
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed. help me, please!

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
