### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thakuradi** [PatrickAlphaC/hardhat-simple-storage-fcc#49]
there is an error coming in.
yarn add hardat-gas-reporter --D
yarn add v1.22.15
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/hardat-gas-reporter: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/thakuradi/hh-fcc/ethers-simple-storage/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
