### ISSUE TITLE
Error HH100: Network rinkeby doesn't exist

### ISSUE THREAD

**Issue by iperezluis** [PatrickAlphaC/hardhat-simple-storage-fcc#5]
Error HH100: Network rinkeby doesn't exist

For more info go to https://hardhat.org/HH100 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.

**Comment by PatrickAlphaC** [comment]
Can you add more information and ask your question in the main repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js

1. What command did you run?
2. What is the exact output?
3. What does your `hardhat.config.js` look like? 

Closing this, feel free to make it there.
