### ISSUE TITLE
deployment error

### ISSUE THREAD

**Issue by malommey** [PatrickAlphaC/hardhat-simple-storage-fcc#51]
no network error during deployment

SEPOLIA_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/your-api-key
PRIVATE_KEY= 26cf5e0fcef9ff22611152f5dfd9214669ac807d7ade8d24266e9ac9b109bb69

'could not detect network',

**Comment by PatrickAlphaC** [comment]
That's not your private key is it???

**Comment by malommey** [comment]
> That's not your private key is it???

it is sir. but no real fund on the account

**Comment by PatrickAlphaC** [comment]
Ah ok.

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
