### ISSUE TITLE
getting this issue on running command yarn hardhat run scripts/deploy.js

### ISSUE THREAD

**Issue by drleavio** [PatrickAlphaC/hardhat-simple-storage-fcc#52]
HardhatError: HH700: Artifact for contract "SimpleStorage" not found.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
