### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'wait')

### ISSUE THREAD

**Issue by YUANrl** [PatrickAlphaC/hardhat-simple-storage-fcc#62]
Guys，When I run this piece of code, I encounter a TypeError. How should I resolve it?

// imports
const { ethers, run, network } = require("hardhat");

// async main
async function main() {
  const SimpleStorageFactory = await ethers.getContractFactory("SimpleStorage");
  console.log("Deploying contract...");

  const simpleStorage = await SimpleStorageFactory.deploy();
  await simpleStorage.waitForDeployment();
  console.log(`Deployed contract to: ${simpleStorage.target}`);
  // what happens when we deploy to our hardhat network?

  if (network.config.chainId == 11155111 && process.env.ETHERSCAN_API_KEY) {
    console.log("Waiting for block confirmations...");
    await simpleStorage.deployTransaction.wait(6);     //HERE!!!
    await verify(simpleStorage.target, []);
  }

**Comment by StevenHung0318** [comment]
Tyr this
await simpleStorage.deploymentTransaction().wait(6)
