### ISSUE TITLE
Verifying contract... Verification failed: UnexpectedError: An unexpected error occurred during the verification process. Please report this issue to the Hardhat team. Error Details: Invalid API Key

### ISSUE THREAD

**Issue by Firdose09** [PatrickAlphaC/hardhat-simple-storage-fcc#68]
const { ethers, run, network } = require("hardhat")
require("@nomicfoundation/hardhat-verify")

async function verifyContract() {
    const chainId = network.config.chainId

    const simpleStorageFactory =
        await ethers.getContractFactory("SimpleStorage")

    const args = []

    console.log(`Deploying...`)
    const simpleStorage = await simpleStorageFactory.deploy(...args)
    await simpleStorage.waitForDeployment()
    console.log(`Deployed!`)
    console.log(`Simple Storage Address: ${simpleStorage.target}`)

    console.log(`Waiting for block confirmations...`)
    await simpleStorage.waitForDeployment() // Wait for 1 confirmation
    console.log(`Confirmed!`)

    // Only verify on testnets or mainnets.
    if (chainId != 31337 && process.env.ETHERSCAN_API_KEY) {
        await simpleStorage.waitForDeployment(6)
        await verify(simpleStorage.target, args) // Passing the target for verification
    }

    const currentValue = await simpleStorage.retrieve()
    console.log(`Current Value is: ${currentValue}`)

    const transactionResponse = await simpleStorage.store(7)
    await transactionResponse.wait(1)
    const updatedValue = await simpleStorage.retrieve()
    console.log(`Updated Value is: ${updatedValue}`)
}

const verify = async (contractTarget, args) => {
    // Changed parameter name from contractAddress to contractTarget
    console.log("Verifying contract...")
    try {
        await run("verify:verify", {
            address: contractTarget, // Changed from address to contractTarget
            constructorArguments: args,
        })
        console.log("Verification successful!")
    } catch (e) {
        if (e.message.toLowerCase().includes("already verified")) {
            console.log("Already verified!")
        } else {
            console.log("Verification failed:", e)
        }
    }
}

verifyContract()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("Error:", error)
        process.exit(1)
    })

**Comment by Firdose09** [comment]
plss solve my error i tried but didn't get i nearly wasted 1 week solving this issue!!

**Comment by PatrickAlphaC** [comment]
Thanks for this issue! 

Can you:
1. Make this a discussion on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
