### ISSUE TITLE
lesson 6 Hardhat - HardHat issue Verifying to Sepolia

### ISSUE THREAD

**Issue by tanakajera** [PatrickAlphaC/hardhat-simple-storage-fcc#71]
// imports
const { ethers, run, network } = require("hardhat")
require("@nomicfoundation/hardhat-ethers")

// async main
async function main() {
    const SimpleStorageFactory =
        await ethers.getContractFactory("SimpleStorage")
    console.log("Deploying Contract...")
    const simpleStorage = await SimpleStorageFactory.deploy()
    await simpleStorage.getDeployedCode()
    console.log(`Deployed Contract to: ${simpleStorage.target}`)
    // whats happened when we deploy to our hardhat network?
    // console.log(network.config)
    if (network.config.chainId === 11155111 && process.env.ETHERSCAN_API_KEY) {
        console.log("Waiting blocks txes...")
        await simpleStorage.deploytransaction().wait(6)
        await verify(simpleStorage.target, [])
    }
    // const currentValue = await simpleStorage.retrieve()
    // console.log(`Current Value is: ${currentValue}`)

    // update current value
    const transactionResponse = await simpleStorage.store(7)
    await transactionResponse.wait(1)
    const updatedValue = await simpleStorage.retrieve()
    console.log(`Updated value is:${updatedValue}`)
}

// async function verify(contractAddress, args) {
const verify = async (contractAddress, args) => {
    console.log("Verifying contract...")
    try {
        await run("verify: verify", {
            address: contractAddress,
            constuctorAddress: args,
        })
    } catch (e) {
        if (e.message.toLowerCase().inlcudes("already verified")) {
            console.log("Already Verified")
        } else {
            console.log(e)
        }
    }
}

// main
main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error)
        process.exit(1)
    })

for some reason my deploy script doesnt even attempt to verify. can anyone help?

**Comment by PatrickAlphaC** [comment]
I'm going to be deprecating this repo for cyfrin updraft soon. Sorry this isn't working!

https://updraft.cyfrin.io/

**Comment by tanakajera** [comment]
> I'm going to be deprecating this repo for cyfrin updraft soon. Sorry this isn't working!
> 
> https://updraft.cyfrin.io/

will this have the same amount of content as this one? as i have just seen the cyfrin one only has 5 hrs currently..

**Comment by PatrickAlphaC** [comment]
There are 6 courses with over 70+ hours of content total.

So, it's actually much more :)
