### ISSUE TITLE
Possible issue with tsconfig.json

### ISSUE THREAD

**Issue by webthethird** [PatrickAlphaC/hardhat-simple-storage-fcc#9]
Hello,

At the end of Lesson 6, during the Typescript section, I ran into an unexpected issue that didn't appear to affect you in the video. Here's the breakdown of what went wrong and how I fixed it:

After copying over the contents of tsconfig.json from this repo, I had no issues converting the deploy and hardhat-config from .js to .ts. However, when I did the same with the block-number task I ran into the following error:
![Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)
](https://user-images.githubusercontent.com/6509209/174692171-54f92319-8321-4c2d-9f88-7d691e4901ec.png)
`Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)`

I thought this was odd, but after poking around for a few minutes I noticed this line in the tsconfig.json file I copied:
```json
"include": ["./scripts", "./test"],
```
It occurred to me that "./tasks" was missing, and as soon as I added that to the list my error disappeared!

However, I find it curious that this didn't appear to be necessary in the video, as there's no sign of the same error in the screenshot of the video below:
![image](https://user-images.githubusercontent.com/6509209/174692691-66f7cc55-9c91-4468-a9dd-37372e214f51.png)

It seems possible that this is due to some difference between dependency versions, since I added them myself as I followed along rather than copy your package.json contents. These are the versions specified in mine:
```json
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "@nomiclabs/hardhat-waffle": "^2.0.0",
    "@typechain/ethers-v5": "^10.1.0",
    "@typechain/hardhat": "^6.1.2",
    "@types/chai": "^4.3.1",
    "@types/mocha": "^9.1.1",
    "@types/node": "^18.0.0",
    "chai": "^4.2.0",
    "dotenv": "^16.0.1",
    "ethereum-waffle": "^3.0.0",
    "ethers": "^5.0.0",
    "hardhat": "^2.9.9",
    "hardhat-gas-reporter": "^1.0.8",
    "prettier": "^2.7.1",
    "prettier-plugin-solidity": "^1.0.0-beta.19",
    "solidity-coverage": "^0.7.21",
    "ts-node": "^10.8.1",
    "typechain": "^8.1.0",
    "typescript": "^4.7.4"
  }
```

Regardless, this is the modified tsconfig.json file that resolved my error:
```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist"
  },
  "include": ["./scripts", "./test", "./tasks"],
  "files": ["./hardhat.config.ts"]
}
```

**Comment by webthethird** [comment]
Related to this: 
Once I made that change in tsconfig.json, I followed your instructions and ran the command `yarn hardhat run scripts/deploy.ts` but encountered the error below:
```
An unexpected error occurred:

tasks/block-number.ts:8:10 - error TS7006: Parameter 'taskargs' implicitly has an 'any' type.

8   async (taskargs, hre) => {
           ~~~~~~~~
tasks/block-number.ts:8:20 - error TS7006: Parameter 'hre' implicitly has an 'any' type.

8   async (taskargs, hre) => {
                     ~~~
```

This was easily resolved by specifying the types, as seen below:
```ts
import { task } from "hardhat/config"
import { HardhatRuntimeEnvironment } from "hardhat/types"

/**
 * My first Hardhat task!
 */
export default task("block-number", "Prints the current block number").setAction(
  // Called an "anonymous function" in Javascript
  async (taskargs: any[], hre: HardhatRuntimeEnvironment) => {
    /**
     * hre: Hardhat runtime environment
     */
    const blockNumber = await hre.ethers.provider.getBlockNumber()
    console.log(`Current block number: ${blockNumber}`)
  }
)
```

**Comment by PatrickAlphaC** [comment]
Hmm... likely something to do with the tasks stuff... do you know if me typescript branch is having these issues? 

Wondering if this makes sense to update that repo.

**Comment by webthethird** [comment]
> do you know if me typescript branch is having these issues?

No, your typescript branch in this repo is not having these issues. I wish I knew what caused this in mine! 

Anyway, I suppose there's no need to take any action if we can't replicate the issue.

**Comment by PatrickAlphaC** [comment]
Perhaps try re git cloning the repo and see if you still get the issue?

**Comment by webthethird** [comment]
Oh I never had any issues with this repo specifically, only when I created my own and added the dependencies using yarn without specifying the same version numbers as you have in your `package.json`. I only opened this issue because I thought others might run into the same issue when following along and building the app from scratch, rather than cloning this repo and having all the code already written!
